package com.univelect.dao;
import com.univelect.util.DBConnection;import com.univelect.util.PasswordUtil;import java.sql.*;
public class AdminDAO {
 private void requireAdmin(int uid) throws SQLException {try(Connection c=DBConnection.getConnection();PreparedStatement p=c.prepareStatement("SELECT role FROM users WHERE id=?")){p.setInt(1,uid);try(ResultSet r=p.executeQuery()){if(!r.next()||!"ADMIN".equalsIgnoreCase(r.getString(1)))throw new SecurityException("Administrator access required.");}}}
 public void createElection(int uid,String title,String code,String desc,String start,String end,int voters)throws SQLException{requireAdmin(uid);String q="INSERT INTO elections(title,code,description,start_date,end_date,status,total_registered_voters) VALUES(?,?,?,?,?,'DRAFT',?)";try(Connection c=DBConnection.getConnection();PreparedStatement p=c.prepareStatement(q)){p.setString(1,title);p.setString(2,code);p.setString(3,desc);p.setString(4,start);p.setString(5,end);p.setInt(6,voters);p.executeUpdate();}}
 public void setStatus(int uid,int id,String status)throws SQLException{requireAdmin(uid);try(Connection c=DBConnection.getConnection()){c.setAutoCommit(false);if("ACTIVE".equals(status))try(PreparedStatement p=c.prepareStatement("UPDATE elections SET status='CLOSED' WHERE status='ACTIVE' AND id<>?")){p.setInt(1,id);p.executeUpdate();}try(PreparedStatement p=c.prepareStatement("UPDATE elections SET status=? WHERE id=?")){p.setString(1,status);p.setInt(2,id);p.executeUpdate();}c.commit();}}
 public void deleteElection(int uid,int id)throws SQLException{requireAdmin(uid);try(Connection c=DBConnection.getConnection();PreparedStatement p=c.prepareStatement("DELETE FROM elections WHERE id=?")){p.setInt(1,id);p.executeUpdate();}}
 public void addPosition(int uid,int eid,String title,String desc)throws SQLException{requireAdmin(uid);String q="INSERT INTO positions(election_id,title,description,max_votes) VALUES(?,?,?,1)";try(Connection c=DBConnection.getConnection();PreparedStatement p=c.prepareStatement(q)){p.setInt(1,eid);p.setString(2,title);p.setString(3,desc);p.executeUpdate();}}
 public void reviewCandidate(int uid,int id,String status)throws SQLException{requireAdmin(uid);try(Connection c=DBConnection.getConnection();PreparedStatement p=c.prepareStatement("UPDATE candidates SET status=? WHERE id=?")){p.setString(1,status);p.setInt(2,id);p.executeUpdate();}}
 public void removeCandidate(int uid,int id)throws SQLException{requireAdmin(uid);try(Connection c=DBConnection.getConnection();PreparedStatement p=c.prepareStatement("DELETE FROM candidates WHERE id=?")){p.setInt(1,id);p.executeUpdate();}}
 public void addStudent(int uid,String name,String sid,String email,String department,int year,String password)throws SQLException{requireAdmin(uid);String q="INSERT INTO users(student_id,name,email,department,year,password_hash,role,status,avatar) VALUES(?,?,?,?,?,?,'STUDENT','ACTIVE',?)";try(Connection c=DBConnection.getConnection();PreparedStatement p=c.prepareStatement(q)){p.setString(1,sid);p.setString(2,name);p.setString(3,email);p.setString(4,department);p.setInt(5,year);p.setString(6,PasswordUtil.sha256(password));p.setString(7,"https://ui-avatars.com/api/?name="+java.net.URLEncoder.encode(name,java.nio.charset.StandardCharsets.UTF_8)+"&background=6366f1&color=fff");p.executeUpdate();}}
 public void removeStudent(int uid,int id)throws SQLException{requireAdmin(uid);try(Connection c=DBConnection.getConnection();PreparedStatement p=c.prepareStatement("DELETE FROM users WHERE id=? AND role<>'ADMIN'")){p.setInt(1,id);p.executeUpdate();}}
 public void nominate(int uid,int eid,int pid,String manifesto)throws SQLException{String q="INSERT INTO candidates(user_id,election_id,position_id,tagline,manifesto,status) VALUES(?,?,?,?,?,'PENDING')";try(Connection c=DBConnection.getConnection();PreparedStatement p=c.prepareStatement(q)){p.setInt(1,uid);p.setInt(2,eid);p.setInt(3,pid);p.setString(4,"New Candidate");p.setString(5,manifesto);p.executeUpdate();}}
}
